### ISSUE TITLE
Detailed error messages

### ISSUE THREAD

**Issue by danilofreire** [BrazilianPublicData/congressbr#26]
I've tested all functions and they're running without issues. Hurray! 

However, the error messages are not very informative. I could rarely figure out what my mistakes were from the code output. Maybe we (I?) should put some effort on that? What do you think?

p.s.: This issue closes [#25](https://github.com/RobertMyles/congressbr/issues/25). This one is more general.

**Comment by RobertMyles** [comment]
Great :-) 

Which functions are giving uninformative error messages? Do you want to add some messages you think would be better?

**Comment by danilofreire** [comment]
Many of them do, in fact. I can surely write some of the error messages, but probably not all. Some of the errors messages are the same despite resulting from different user mistakes, so I don't know exactly how to deal with that. Should we have a chat and try to write new messages together? :smiley:

**Comment by RobertMyles** [comment]
Sure. Hmm, maybe if you leave a checklist of the functions returning errors here, we can go through them and fix one by one

**Comment by danilofreire** [comment]
Sure, will do!
