### ISSUE TITLE
chamber documentation

### ISSUE THREAD

**Issue by RobertMyles** [BrazilianPublicData/congressbr#31]
remove:
```
#' @note Requesting data from a long period of time with \code{details = TRUE} will
#' return a large object in terms of memory. It will also be rather unwieldy, with
#' many columns.
```

**Comment by danilofreire** [comment]
Have you removed that part already? If not, I'll do it. We also have to give more examples in the documentation. I can do it on Saturday if that's okay.

**Comment by RobertMyles** [comment]
I removed one or two, but I think all the Chamber documentation has it. Feel free to do it when you can :-)
